# Site settings
title: "Meet Sakura"
description: "Sakura Inomata's Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Sakura Inomata"
# resume_title:                   "VP of Global Communications"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "saachorin.0415@icloud.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "07934531650"
resume_contact_address:         "Uxbridge, England"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>A hardworking, energetic worker with a desire to make guests feel welcome. Eager to demonstrate advanced skills in food safety & customer service to new, rewarding opportunities. Collaborative with wait staff and kitchen workers to exceed expectations with fast, delicious food.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  resume_instagram_url:         "https://www.instagram.com/saachorin/"
  resume_website_url:           "https://ahandsel.github.io/meet-sakura/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: Restart the local Jekyll server when you edit _config.yml file
